# Generated by Django 4.2.6 on 2023-10-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('messages', models.TextField()),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('arabic', '1'), ('forign', '2')], max_length=9)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Full_name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=10)),
                ('Photo', models.ImageField(blank=True, upload_to='profile/')),
                ('experience', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userType',
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MusicApp.teachers'),
            preserve_default=False,
        ),
    ]
