# Generated by Django 4.2.6 on 2023-10-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0003_testimonial_rename_courses_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
