# Generated by Django 4.2.6 on 2023-10-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0004_remove_teacher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('arabic', 'عربية'), ('forign', 'غربية')], max_length=9),
        ),
    ]
