# Generated by Django 4.2.6 on 2023-10-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0006_alter_course_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='price',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
