# Generated by Django 4.2.6 on 2023-11-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0007_remove_contact_price_contact_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Photo', models.ImageField(blank=True, upload_to='blogs/')),
                ('description', models.TextField()),
            ],
        ),
    ]
