# Generated by Django 4.2.6 on 2023-11-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0008_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
